### PR TITLE
Update site files

### PR DESCRIPTION
**Pull request by psolymos**
This PR contains the files currently deployed at <https://wbi.predictiveecology.org> with the apps listed.

### CODE REVIEW

**Comment by psolymos** [comment]
I was editing the rendered output. But we can look into that. That would also work well with the webhook that we have set up (we can pull the contents after a successful build step).

Would it be OK if the theme is different but the content is the same? Using a different template might be easier, I recall I was having some difficulties with the top navigation bar and that is why I chose to edit the HTML directly.

**Comment by eliotmcintire** [comment]
Theme change is fine. Currently, the top menu is created by the `_site.yml` file in the `website` folder. It relies on having an `Rmd` for each page... so there would have to be an `apps.Rmd` file inside `website` folder, and then add `apps.html` to the `_site.yml` file as per the other ones already there.

**Comment by eliotmcintire** [comment]
I just made the app.Rmd file and added it to the _site.yml and it looks
like it all works. I will make a PR so everyone can see it.

**Comment by eliotmcintire** [comment]
https://htmlpreview.github.io/?https://raw.githubusercontent.com/PredictiveEcology/WesternBorealInitiative/appsMenu/docs/index.html


It is not getting the favicon.ico for some reason... the file is there.
Maybe it is because it is using the `htmlpreview` service that the favicon
doesn't show up in the browser tab

**Comment by psolymos** [comment]
Favicon is usually a browser caching problem. It should work once deployed if the file is served correctly.

**Comment by eliotmcintire** [comment]
So, I will accept the PR and it seems to be fine. If something breaks, then
we can revert.

But it means that we now build the site with the Rstudio button (Build
website on the "Build" tab) -- which is MUCH faster than the command:
`system.time(rmarkdown::render_site(input = "website", encoding = 'UTF-8'))`

**Comment by psolymos** [comment]
@eliotmcintire Is the the following?

1. Make changes to rmd (`website`) folder locally
2. Build the site (RStudio button or `render_site()`)
3. Git push the changes to master

The benefit is that you can check the output locally and push when you like it.

I am asking because of the webhook that should deploy the static content deployment to the server. It would clone the repo and copy the `docs` folder to its destination.

Can you give me write access to this repo so that I can set up the webhook secret? Thanks.

**Comment by eliotmcintire** [comment]
"yes" that is right. The web hook is fine also. There is a tradition in the
Rmarkdown world because of how R packages had vignettes in a folder called
"vignettes", that the user didn't change things in a `docs` folder...
rather the various tools in the toolchain (pkgdown, rmarkdown) would build
the site and push everything to the `docs` folder, which essential was a
"read only" folder.

**Comment by eliotmcintire** [comment]
> Can you give me write access to this repo so that I can set up the webhook secret? Thanks.

Done

**Comment by psolymos** [comment]
> > Can you give me write access to this repo so that I can set up the webhook secret? Thanks.
> 
> Done

Looks like I need to be an admin to see the Settings.

**Comment by psolymos** [comment]
> "yes" that is right. The web hook is fine also. There is a tradition in the Rmarkdown world because of how R packages had vignettes in a folder called "vignettes", that the user didn't change things in a `docs` folder... rather the various tools in the toolchain (pkgdown, rmarkdown) would build the site and push everything to the `docs` folder, which essential was a "read only" folder.

That is fair. However, I don't quite like having zillion files in the docs folder as it happens with HTML rendering (vignettes are Rmd or LaTeX without the locally served js/css assets). So I usually push pages to the `gh-pages` branch when hosting with gh pages. This site is a bit different though, contents are served from the Alliance VM.

**Pull request merged**
